[2024-08-05T13:56:04.982+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T13:56:05.004+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Nairobi manual__2024-08-05T10:55:18.903534+00:00 [queued]>
[2024-08-05T13:56:05.011+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Nairobi manual__2024-08-05T10:55:18.903534+00:00 [queued]>
[2024-08-05T13:56:05.011+0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-05T13:56:05.029+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_air_pollution_data_Nairobi> on 2024-08-05 10:55:18.903534+00:00
[2024-08-05T13:56:05.033+0300] {standard_task_runner.py:64} INFO - Started process 74295 to run task
[2024-08-05T13:56:05.037+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'air_pollution_data_dag', 'fetch_air_pollution_data_Nairobi', 'manual__2024-08-05T10:55:18.903534+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/air_pollution_data_dag.py', '--cfg-path', '/tmp/tmp8_p_5psf']
[2024-08-05T13:56:05.037+0300] {standard_task_runner.py:91} INFO - Job 290: Subtask fetch_air_pollution_data_Nairobi
[2024-08-05T13:56:05.074+0300] {task_command.py:426} INFO - Running <TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Nairobi manual__2024-08-05T10:55:18.903534+00:00 [running]> on host std21092
[2024-08-05T13:56:05.145+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_pollution_data_dag' AIRFLOW_CTX_TASK_ID='fetch_air_pollution_data_Nairobi' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T10:55:18.903534+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T10:55:18.903534+00:00'
[2024-08-05T13:56:05.146+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T13:56:07.103+0300] {logging_mixin.py:188} INFO - Erreur lors de la récupération des données pour Nairobi: 401 - {"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}
[2024-08-05T13:56:07.104+0300] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T13:56:07.104+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T13:56:07.117+0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=air_pollution_data_dag, task_id=fetch_air_pollution_data_Nairobi, run_id=manual__2024-08-05T10:55:18.903534+00:00, execution_date=20240805T105518, start_date=20240805T105605, end_date=20240805T105607
[2024-08-05T13:56:07.178+0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T13:56:07.246+0300] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-05T13:56:07.251+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
