[2024-08-05T13:40:54.924+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T13:40:54.956+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Los_Angeles manual__2024-08-05T10:40:51.003598+00:00 [queued]>
[2024-08-05T13:40:54.964+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Los_Angeles manual__2024-08-05T10:40:51.003598+00:00 [queued]>
[2024-08-05T13:40:54.964+0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-05T13:40:54.978+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_air_pollution_data_Los_Angeles> on 2024-08-05 10:40:51.003598+00:00
[2024-08-05T13:40:54.983+0300] {standard_task_runner.py:64} INFO - Started process 67743 to run task
[2024-08-05T13:40:54.986+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'air_pollution_data_dag', 'fetch_air_pollution_data_Los_Angeles', 'manual__2024-08-05T10:40:51.003598+00:00', '--job-id', '273', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp9p6wdxf1']
[2024-08-05T13:40:54.986+0300] {standard_task_runner.py:91} INFO - Job 273: Subtask fetch_air_pollution_data_Los_Angeles
[2024-08-05T13:40:55.018+0300] {task_command.py:426} INFO - Running <TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Los_Angeles manual__2024-08-05T10:40:51.003598+00:00 [running]> on host std21092
[2024-08-05T13:40:55.085+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_pollution_data_dag' AIRFLOW_CTX_TASK_ID='fetch_air_pollution_data_Los_Angeles' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T10:40:51.003598+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T10:40:51.003598+00:00'
[2024-08-05T13:40:55.087+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T13:40:56.461+0300] {logging_mixin.py:188} INFO - Erreur lors de la récupération des données pour Los_Angeles
[2024-08-05T13:40:56.462+0300] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T13:40:56.462+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T13:40:56.475+0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=air_pollution_data_dag, task_id=fetch_air_pollution_data_Los_Angeles, run_id=manual__2024-08-05T10:40:51.003598+00:00, execution_date=20240805T104051, start_date=20240805T104054, end_date=20240805T104056
[2024-08-05T13:40:56.523+0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T13:40:56.596+0300] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-05T13:40:56.601+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
